clear; clc; close all;
rng(0)
run('setupHover.m');

mdl = 'hoverSim_pid_RL';
open_system(mdl);

obsInfo = rlNumericSpec([2 1], ...
    'LowerLimit', [-inf; -inf], ...
    'UpperLimit', [ inf;  inf]);
obsInfo.Name        = 'observations';
obsInfo.Description = 'pitch_rate_err, p_dot';

actInfo = rlNumericSpec([1 1], ...
    'LowerLimit', -1, ...
    'UpperLimit',  1);
actInfo.Name = 'Ki_action';

run('createAgent_pitch_rate_i.m');

agentBlk = 'hoverSim_pid_RL/Rate_PID/pitch_rate_pid/RL_pitch_rate_i';
env = rlSimulinkEnv(mdl, agentBlk, obsInfo, actInfo);

trainOpts = rlTrainingOptions( ...
    'MaxEpisodes',                300,  ...
    'MaxStepsPerEpisode',         1500, ...
    'ScoreAveragingWindowLength', 20,   ...
    'Verbose',                    true, ...
    'Plots',                      'training-progress', ...
    'StopTrainingCriteria',       'AverageReward', ...
    'StopTrainingValue',          1200);

trainingStats = train(pitch_rate_i, env, trainOpts);

save('trained_pitch_rate_i.mat', 'pitch_rate_i', 'trainingStats');