clear; clc; close all;
rng(0)
run('setupHover.m');

mdl = 'hoverSim_pid_RL';
open_system(mdl);

obsInfo = rlNumericSpec([2 1], ...
    'LowerLimit', [-inf; -inf], ...
    'UpperLimit', [ inf;  inf]);
obsInfo.Name = 'observations';
obsInfo.Description = 'roll_err, roll';

actInfo = rlNumericSpec([1 1], ...
    'LowerLimit', -1, ...
    'UpperLimit',  1);
actInfo.Name = 'Kp_action';

run('createAgent_roll_angle_p.m');

agentBlk = 'hoverSim_pid_RL/Angle_PID/roll_angle_pid/RL_roll_angle_p';
env = rlSimulinkEnv(mdl, agentBlk, obsInfo, actInfo);

trainOpts = rlTrainingOptions( ...
    'MaxEpisodes',                300,  ...
    'MaxStepsPerEpisode',         1500, ...
    'ScoreAveragingWindowLength', 20,   ...
    'Verbose',                    true, ...
    'Plots',                      'training-progress', ...
    'StopTrainingCriteria',       'AverageReward', ...
    'StopTrainingValue',          -100);

trainingStats = train(roll_angle_p, env, trainOpts);

save('trained_roll_angle_p.mat', 'roll_angle_p', 'trainingStats');