clear; clc; close all;
rng(0)

run('setupHover.m');

mdl = 'hoverSim_pid_RL';
open_system(mdl);

obsInfo = rlNumericSpec([2 1], ...
    'LowerLimit', [-inf; -inf], ...
    'UpperLimit', [ inf;  inf]);
obsInfo.Name = 'observations';
obsInfo.Description = 'yaw_rate_err, y_dot';

actInfo = rlNumericSpec([1 1], ...
    'LowerLimit', -1, ...
    'UpperLimit',  1);
actInfo.Name = 'Kp_action';

run('createAgent_yaw_rate_p.m');

agentBlk = 'hoverSim_pid_RL/Rate_PID/yaw_rate_pid/RL_yaw_rate_p';
env = rlSimulinkEnv(mdl, agentBlk, obsInfo, actInfo);

trainOpts = rlTrainingOptions( ...
    'MaxEpisodes',                300,  ...
    'MaxStepsPerEpisode',         1500, ...
    'ScoreAveragingWindowLength', 20,   ...
    'Verbose',                    true, ...
    'Plots',                      'training-progress', ...
    'StopTrainingCriteria',       'AverageReward', ...
    'StopTrainingValue',          1200);

trainingStats = train(yaw_rate_p, env, trainOpts);

save('trained_yaw_rate_p.mat', 'yaw_rate_p', 'trainingStats');