clear; clc; close all;
run('setupHover.m');
mdl = 'hoverSim_pid';
open_system(mdl);
kp_var = optimizableVariable('kp_yaw_angle', [0, 25], 'Type', 'real');
results = bayesopt(@objectiveYawAngleP, kp_var, ...
'MaxObjectiveEvaluations',  30, ...
'IsObjectiveDeterministic', true, ...
'AcquisitionFunctionName',  'expected-improvement-plus', ...
'Verbose',                   1, ...
'PlotFcn', {@plotObjectiveModel, @plotMinObjective});
best_Kp = results.XAtMinObjective.kp_yaw_angle;
fprintf('\nBeste kp_yaw_angle: %.4f\n', best_Kp);
kp_yaw_angle = best_Kp;
save('tuned_yaw_angle_p.mat', 'kp_yaw_angle');
disp('Lagret til tuned_yaw_angle_p.mat');